import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return <>
    <Head>
      <title>Personal Budge</title>
      <meta name="description" content="Generated by create next app" />

    </Head>
    <h1 className="text-center text-2xl font-bold">My Personal Budget Management </h1>

  </>
}

export default Home
